import Head from "next/head";
import Link from "next/link";
import { useCallback, useContext, useEffect, useState } from "react";
import { Hero } from "../components/home-page/hero";
import { Plans } from "../components/home-page/plans";
import { Movies } from "../components/movies";
import { PlanContext } from "../contexts/plans";
import { HeroType } from "../models/interfaces/hero";
import { Movie } from "../models/interfaces/movie";
import { Plan } from "../models/interfaces/plans";
import { getHero } from "../utils/hero";
import { getAllMovies, getEnabledMovies } from "../utils/movie";

const Home = ({
  moviesList,
  hero,
}: {
  moviesList: Movie[];
  hero: HeroType;
}) => {
  const [plansList, setPlansList] = useState<Plan[] | null>(null);
  const planContext = useContext(PlanContext);

  const getUrlPlan = useCallback(() => {
    if (planContext?.numberClicks === 3 || planContext?.numberClicks === 10) {
      return "/api/plans/full";
    }
    return "/api/plans/2";
  }, [planContext?.numberClicks]);

  const getInitPlans = useCallback(async () => {
    const urlPlans = getUrlPlan();
    try {
      const response = await fetch(urlPlans);
      if (!response.ok) {
        console.log("getInitPlans response.ok");
        const text = await response.text();
        throw new Error(text);
      }
      const jsonData = await response.json();
      setPlansList(jsonData);
      return jsonData;
    } catch (error) {
      console.log("Something went wrong. getInitPlans", error);
    }
  }, [getUrlPlan, planContext?.numberClicks]);

  useEffect(() => {
    getInitPlans();
  }, [getInitPlans, planContext?.numberClicks]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-y-14">
        <Hero price={hero.price} description={hero.description} />
        <Plans plans={plansList} />
        <Link href="/all-plans">Show all Plans</Link>
        <Movies movies={moviesList} />
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const allMovies: Movie[] = await getAllMovies();
  const hero: HeroType = await getHero();
  let formatedAllMovies: Movie[] = [];
  if (allMovies && allMovies?.length) {
    formatedAllMovies = allMovies;
  }
  const moviesFilter: Movie[] = getEnabledMovies(formatedAllMovies);
  return {
    props: {
      moviesList: moviesFilter,
      hero,
    },
    revalidate: 10,
  };
}

export default Home;
