import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "../components/home-page/hero";
import { Plans } from "../components/home-page/plans";
import { Movies } from "../components/movies";
import { MoviesConstant } from "../constants/movies";
import { PlansConstant } from "../constants/plans";
import { Movie } from "../models/interfaces/movie";
import { Plan } from "../models/interfaces/plans";

const Home = ({
  plansList,
  moviesList,
}: {
  plansList: Plan[];
  moviesList: Movie[];
}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-y-14">
        <Hero price="9.991,67" />
        <Plans plans={plansList} />
        <Movies movies={moviesList} />
      </div>
    </div>
  );
};

export async function getStaticProps() {
  return {
    props: { plansList: PlansConstant, moviesList: MoviesConstant },
    revalidate: 10
  };
}

export default Home;
